/**
 * Gruppikonernas svenska namn (0.65.0, #265, granskningen av PR 266).
 *
 * ⛔ VARFÖR. Knapparnas namn var Lucides engelska filnamn ("music 2", "audio waveform"), och en skärmläsare läste upp dem så.
 * Varje ikon har nu ett svenskt namn som säger vad den FÖRESTÄLLER, och namnen är unika: två ikoner med samma motiv
 * (bok och uppslagen bok, jordglob och jorden) går att skilja åt utan att se dem. Provet `gruppikonsok.test.js` kräver
 * ett namn per ikon i katalogen och inga dubbletter.
 *
 * ⛔ NAMNEN ÄR OCKSÅ SÖKORD. Den som skriver "hörlurar" eller "skiva" hittar ikonen på dess svenska namn, utan att
 * synonymlistan behöver känna ordet.
 */
export const GRUPPIKON_SVENSKA = Object.freeze({
  activity: "Pulskurva",
  album: "Skivalbum",
  anchor: "Ankare",
  apple: "Äpple",
  archive: "Arkivlåda",
  atom: "Atom",
  "audio-lines": "Ljudvåg",
  award: "Utmärkelse",
  baby: "Bebis",
  backpack: "Ryggsäck",
  banknote: "Sedel",
  beer: "Ölsejdel",
  bell: "Klocka som ringer",
  bike: "Cykel",
  bird: "Fågel",
  book: "Bok",
  "book-open": "Uppslagen bok",
  bot: "Robot",
  brain: "Hjärna",
  briefcase: "Portfölj",
  bug: "Insekt",
  "building-2": "Kontorshus",
  bus: "Buss",
  cake: "Tårta",
  calculator: "Miniräknare",
  calendar: "Kalender",
  camera: "Kamera",
  car: "Bil",
  caravan: "Husvagn",
  carrot: "Morot",
  castle: "Slott",
  cat: "Katt",
  "chart-line": "Linjediagram",
  "chart-pie": "Cirkeldiagram",
  "chef-hat": "Kockmössa",
  church: "Kyrka",
  clapperboard: "Filmklappa",
  "clipboard-list": "Checklista",
  clock: "Klocka",
  cloud: "Moln",
  "cloud-cog": "Moln med kugghjul",
  code: "Kod",
  coffee: "Kaffekopp",
  coins: "Mynt",
  compass: "Kompass",
  contact: "Kontaktkort",
  cookie: "Kaka",
  cpu: "Processor",
  "credit-card": "Betalkort",
  cross: "Kors",
  crosshair: "Sikte",
  crown: "Krona",
  "cup-soda": "Läskmugg",
  database: "Databas",
  "dice-5": "Tärning",
  disc: "Skiva",
  dog: "Hund",
  drama: "Teatermasker",
  droplet: "Droppe",
  drum: "Trumma",
  dumbbell: "Hantel",
  earth: "Jorden med kontinenter",
  factory: "Fabrik",
  "file-text": "Dokument",
  film: "Filmrulle",
  fish: "Fisk",
  flag: "Flagga",
  flame: "Låga",
  "flask-conical": "Kolv",
  flower: "Blomma",
  folder: "Mapp",
  footprints: "Fotspår",
  "gamepad-2": "Spelkontroll",
  gem: "Ädelsten",
  gift: "Present",
  globe: "Jordglob",
  goal: "Mål med flagga",
  "graduation-cap": "Studentmössa",
  guitar: "Gitarr",
  hammer: "Hammare",
  handshake: "Handslag",
  "hard-hat": "Skyddshjälm",
  hash: "Fyrkant",
  headphones: "Hörlurar",
  heart: "Hjärta",
  "heart-handshake": "Hjärta med handslag",
  "heart-pulse": "Hjärtslag",
  hospital: "Sjukhus",
  hotel: "Hotell",
  house: "Hus",
  image: "Bild",
  inbox: "Inkorg",
  infinity: "Oändlighet",
  joystick: "Styrspak",
  key: "Nyckel",
  landmark: "Pelarbyggnad",
  laptop: "Bärbar dator",
  layers: "Lager",
  leaf: "Löv",
  library: "Bokhylla",
  lightbulb: "Glödlampa",
  "list-music": "Spellista",
  lock: "Lås",
  luggage: "Resväska",
  mail: "Kuvert",
  map: "Karta",
  "map-pin": "Kartnål",
  medal: "Medalj",
  megaphone: "Megafon",
  "message-circle": "Pratbubbla",
  mic: "Mikrofon",
  microscope: "Mikroskop",
  monitor: "Bildskärm",
  moon: "Måne",
  mountain: "Berg",
  music: "Noter",
  newspaper: "Tidning",
  "notebook-pen": "Anteckningsbok",
  package: "Paket",
  paintbrush: "Pensel",
  palette: "Färgpalett",
  "party-popper": "Fest",
  "paw-print": "Tassavtryck",
  "pen-tool": "Reservoarpenna",
  pencil: "Blyertspenna",
  "person-standing": "Stående person",
  phone: "Telefonlur",
  piano: "Piano",
  "piggy-bank": "Spargris",
  pill: "Tablett",
  pizza: "Pizza",
  plane: "Flygplan",
  puzzle: "Pusselbit",
  rabbit: "Kanin",
  radio: "Radio",
  receipt: "Kvitto",
  rocket: "Raket",
  ruler: "Linjal",
  sailboat: "Segelbåt",
  sandwich: "Smörgås",
  scale: "Våg",
  school: "Skola",
  scissors: "Sax",
  server: "Server",
  shield: "Sköld",
  ship: "Fartyg",
  shirt: "Tröja",
  "shopping-bag": "Kasse",
  "shopping-cart": "Kundvagn",
  smartphone: "Mobiltelefon",
  smile: "Leende",
  snowflake: "Snöflinga",
  sparkles: "Gnistor",
  speaker: "Högtalare",
  sprout: "Grodd",
  star: "Stjärna",
  stethoscope: "Stetoskop",
  store: "Butik",
  "sun-medium": "Sol",
  syringe: "Spruta",
  tag: "Etikett",
  target: "Måltavla",
  tent: "Tält",
  terminal: "Terminal",
  theater: "Teatersalong",
  tractor: "Traktor",
  "train-front": "Tåg",
  "tree-pine": "Gran",
  trees: "Träd",
  "trending-up": "Stigande kurva",
  trophy: "Pokal",
  truck: "Lastbil",
  tv: "Teve",
  user: "Person",
  users: "Grupp av personer",
  utensils: "Bestick",
  video: "Videokamera",
  volleyball: "Boll",
  "volume-2": "Volym",
  wallet: "Plånbok",
  warehouse: "Lager med port",
  waves: "Vågor",
  wifi: "Trådlöst nät",
  wine: "Vinglas",
  wrench: "Skiftnyckel",
  zap: "Blixt",
});

/**
 * Namnet en skärmläsare läser och en tooltip visar. Svenska när språket är svenska, annars Lucides namn med mellanslag.
 * @param {string} namn Lucide-namnet. @param {string} [sprak]
 */
export function gruppikonEtikett(namn, sprak = "sv") {
  if (sprak !== "en") {
    // ⛔ `Object.hasOwn`: annars ger "toString" en funktion tillbaka i stället för en etikett.
    if (Object.hasOwn(GRUPPIKON_SVENSKA, namn)) return /** @type {Record<string, string>} */ (GRUPPIKON_SVENSKA)[namn];
  }
  return namn.replace(/-/g, " ");
}
